config/routes.rb
CashForCharity::Application.routes.draw do
  root to: 'charities#index'
  devise_for :users
  resources :charities
  resources :charges, only: [:new, :create]
end

app/models/charity.rb
class Charity < ActiveRecord::Base
  validates :name, presence: true
  validates :mission, presence: true
  validate :check_future_date

  def check_future_date
    if self.founded > Date.today
      errors.add :founded, 'date cannot be in the future.'
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def create
    Stripe.api_key = ENV['SECRET_KEY']
    @amount = params[:amount_pay]
    @charity = Charity.find(params[:charity_id])
    customer = Stripe::Customer.create(
      :email => current_user.email,
      :card  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => @charity.name,
      :currency    => 'usd'
    )

  redirect_to root_path

  rescue Stripe::CardError => e
    flash[:alert] = e.message
    redirect_to charity_path(@charity)
  end

end

app/controllers/charities_controller.rb
class CharitiesController < ApplicationController

  def new
    @charity = Charity.new
  end

  def create
    @charity = Charity.new(charity_params)

    if @charity.save
      flash[:notice] = "Your charity was created!"
      redirect_to root_path
    else
      flash[:alert] = "There was an error creating your charity."
      render 'new'
    end
  end

  def index
    @charties = Charity.all
  end

  def show
    @charity = Charity.find(params[:id])

  end

  def update
    @charity = Charity.find(params[:id])
    if @charity.update(charity_params)
      redirect_to :back
    else
      flash[:alert] = "There was an error editing your charity."
      render 'show'
    end
  end

  def destroy
    @charity = Charity.find(params[:id])
    @charity.destroy
    redirect_to root_path
  end

private
  def charity_params
    params.require(:charity).permit(:name, :mission, :description, :founded)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/charges/_form.html.erb
<%= form_tag charges_path, id: 'payment-form' do %>
  <article>
    <%= hidden_field_tag :charity_id, @charity.id %>
    <div class="form-group">
      <%= label_tag :amount_pay, "Donation Amount" %>
      <%= number_field_tag :amount_pay, nil, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= label_tag :card_number, "Credit Card Number" %>
      <%= text_field_tag :card_number, nil, name: nil, class: "form-control", data: {stripe: "number" } %>
    </div>
    <div class="form-group">
      <%= label_tag :card_code, "Security Code on Card (CVV)" %>
      <%= text_field_tag :card_code, nil, name: nil, class: "form-control", data: {stripe: "cvc" } %>
    </div>
    <div class="form-group">
      <%= label_tag :card_month, "Card Expiration" %>
      <%= select_month nil, {add_month_numbers: true}, {name: nil, id: "card_month", data: {stripe: "exp-month"} } %>
      <%= select_year nil, {start_year: Date.today.year, end_year: Date.today.year+15}, {name: nil, id: "card_year", data: {stripe: "exp-year"}} %>
    </div>
  </article>

  <button type="submit" id="customButton" class="btn btn-success">Donate!</button>
<% end %>

app/views/charges/_form_15.html.erb
<%= form_tag charges_path, id: 'payment-form' do %>
  <article>
    <%= hidden_field_tag :charity_id, @charity.id %>
    <%= hidden_field_tag :amount_pay, 15 %>

    <div class="form-group">
      <%= label_tag :card_number, "Credit Card Number" %>
      <%= text_field_tag :card_number, nil, name: nil, class: "form-control", data: {stripe: "number" } %>
    </div>
    <div class="form-group">
      <%= label_tag :card_code, "Security Code on Card (CVV)" %>
      <%= text_field_tag :card_code, nil, name: nil, class: "form-control", data: {stripe: "cvc" } %>
    </div>
    <div class="form-group">
      <%= label_tag :card_month, "Card Expiration" %>
      <%= select_month nil, {add_month_numbers: true}, {name: nil, id: "card_month", data: {stripe: "exp-month"} } %>
      <%= select_year nil, {start_year: Date.today.year, end_year: Date.today.year+15}, {name: nil, id: "card_year", data: {stripe: "exp-year"}} %>
    </div>
  </article>

  <button type="submit" id="customButton" class="btn btn-success">Donate!</button>
<% end %>

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>$5.00</strong>!</h2>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <label class="amount">
      <span>Amount: $5.00</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="500"></script>
<% end %>

app/views/charities/_form.html.erb
<%= render 'layouts/errors', :object => @charity %>
<%= form_for(@charity) do |f| %>
  <div class="form-group">
    <%= f.label :name, "Name *" %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :mission, "Mission *"%>
    <%= f.text_field :mission, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control", rows: 6 %>
  </div>
  <div class="form-group">
    <%= f.label :founded, "Date Founded" %>
    <%= f.date_field :founded, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-success" %>
  </div>
<% end %>

app/views/charities/index.html.erb
<%= content_for(:title, "Home | €ASH2CHARITIE$") %>
<div class="page-header">
  <h1>Cash 2 Charities</h1>
  <small>Give us cash and we give it to charities for you!</small>
</div>

<% @charties.each do |charity| %>
  <div class="col-md-3">
    <div class="well">
      <%= link_to "#{charity.name} : #{charity.mission}", charity_path(charity) %>
    </div>
  </div>
<% end %>

app/views/charities/new.html.erb
<h2>Add a New Charity</h2>
<div class="col-md-7">
  <%= render 'form' %>
  <p class="text-danger">* required</p>
</div>

app/views/charities/show.html.erb
<%= render 'layouts/errors', :object => @charity %>
<div class="panel-default panel">
  <div class="panel-heading">
    <h1><%= @charity.name %></h1>
  <p><em><%= @charity.mission %></em></p>
  </div>

  <div class="panel-body">
    <p><%= simple_format(@charity.description) %></p>
    <hr>
    <p>Founded: <%= (@charity.founded).strftime('%B %d, %Y') %></p>
  </div>
</div>

<div class="well">
  <div class="row">
    <div class="col-md-4 text-center">
      <h4>Subscribe $15/month</h4>
      <%= link_to "Subscribe", "#", class: 'btn btn-success', data: { toggle: 'modal', target: '#donate-charity-15'} %>
    </div>
    <div class="col-md-4 text-center">
      <h4>Subscribe Custom Amount</h4>
      <%= link_to "Subscribe", "#", class: 'btn btn-success', data: { toggle: 'modal', target: '#donate-charity'} %>
    </div>
    <div class="col-md-4 text-center">
      <h4>One Time Donation</h4>
      <%= link_to "Donate", "#", class: 'btn btn-success', data: { toggle: 'modal', target: '#donate-charity'} %>
    </div>
  </div>
</div>
<br><br><br><br><br><br><br><br><br><br><br><br>
<div class="row">
  <div class="col-md-12">

    <%= link_to 'Edit Charity', "#", class: 'btn btn-info', data: { toggle: 'modal', target: '#edit-charity'} %>
    <%= link_to "Remove Charity", charity_path, method: "delete", data: {confirm: "Are you sure?"}, class: "btn btn-danger" %>
  </div>
</div>

<div class="modal fade" id="donate-charity" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Donate to <%= @charity.name %></h4>
      </div>
      <div class="modal-body">
        <%= render 'charges/form' %>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="donate-charity-15" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Donate to <%= @charity.name %></h4>
      </div>
      <div class="modal-body">
        <%= render 'charges/form_15' %>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="edit-charity" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Edit Charity</h4>
      </div>
      <div class="modal-body">
        <%= render ('form') %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h4>Please Fix These Errors</h4>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <script type="text/javascript" src="https://js.stripe.com/v2/"></script>

  <script type="text/javascript">
    Stripe.setPublishableKey('pk_test_0lKiNk979MHGIqZ0PHcIfch0');

    var stripeResponseHandler = function(status, response) {
      var $form = $('#payment-form');

      if (response.error) {
        // Show the errors on the form
        $form.find('.payment-errors').text(response.error.message);
        $form.find('button').prop('disabled', false);
      } else {
        // token contains id, last4, and card type
        var token = response.id;
        // Insert the token into the form so it gets submitted to the server
        $form.append($('<input type="hidden" name="stripeToken" />').val(token));
        // and re-submit
        $form.get(0).submit();
      }
    };

    $(function($) {
      $('#payment-form').submit(function(e) {
        var $form = $(this);

        // Disable the submit button to prevent repeated clicks
        $form.find('button').prop('disabled', true);

        Stripe.card.createToken($form, stripeResponseHandler);

        // Prevent the form from submitting with the default action
        return false;
      });
    });
    </script>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <div class="row">
      <nav class="navbar navbar-default navbar-fixed-top">
        <%= link_to "Cash 2 Charities", root_path, class: "navbar-brand"  %>
        <%= link_to "Add Charity", new_charity_path, class: "navbar-text"  %>
      </nav>

      <% if flash[:notice] %>
        <div class="alert alert-success">
          <%= flash[:notice] %>
        </div>
      <% elsif flash[:alert] %>
        <div class="alert alert-danger">
          <%= flash[:alert] %>
        </div>

      <% end %>


      <%= yield %>
    </div>
    <br><br><br><br><br><br>

    <hr>
    <div class="row">
      <footer class="text-center">© 2014 €ASH2CHARITIE$.com</footer>
    </div>
  </div>
</body>
</html>